level1 = [
    "WWWWWWWWWWWWWWWWWW",
    "WP         WWW   W",
    "WWWWWWLWWW WWW W W",
    "WWWLLLLWWW     W W",
    "W    WWWWWWWWW W W",
    "W WWKW     WWWKW W",
    "W WWWW WWW WWWWW W",
    "W  WWW W         W",
    "W  WWW W WWWW WW W",
    "WW WKW W WWWW WWWW",
    "WW     W WK   LLLW",
    "WWWWWWWW WWWWWWWWW",
    "W                W",
    "WSWWWLWWWWWW WWWWW",
    "WSWWWLLWWWW  WWWWW",
    "WSWWWDWWWWWWDWWWWW",
    "WSSSS        WWWWW",
    "WWWWWWWWEEWWWWWWWW",
]
level2 = [
    "WWWWWWWWWWWWWWWWWW",
    "WLLLLL    WWWK   W",
    "WWWWWW W WKWWW W W",
    "WWWL   W       W W",
    "W    WWWWWWWW  W W",
    "W WWWWWWWWWWWKW  W",
    "W WWWW    WWWWWW W",
    "W  WWWDWW W      W",
    "WL WWWDWEEWKWLLW W",
    "WW WWWDWWWWSWWWW W",
    "WW     S         W",
    "WW WWWWW WWWWWWWWW",
    "WWKWL            W",
    "WWWWW WWWWWW WWWWW",
    "WWWWW  WWWWL WWWWW",
    "WLLWLL  WW    W KW",
    "WWLLLLW    W    WW",
    "WWWWWWWWP WWWWWWWW",
]
levels = [level1, level2]